- hosts: test
  become: true
  tasks:
    - name: tables
      command: nft delete table inet ismac
      tags: table

    - name: chains
      command: nft flush chain prima isma
      command: nft delete chain ip prima isma
      tags: chain

    - name: rules
      command: nft delete rule test calvochain tcp dport 80 accept
      tags: rule